### ISSUE TITLE
No glucose data to display

### ISSUE THREAD

**Issue by MissBellaButterfly** [jpegjames/glukey#3]
Hi James

I stumbled across this great App via Facebook. I've downloaded it from the App Store on to my iMac (High Sierra) but get the response - 'No glucose data to display'.

I'm outside of the US - would this be causing any problems? 

Cheers
Rach

**Comment by jpegjames** [comment]
Hi Rach,

I'm sorry for the delay—I was out of town. Yes, there is a bug for "international" accounts which I'm finalizing a solution now. I do have a working international build that I can send you via email (support@glukey.info) if you want. 

I'm hoping to have this bug resolved and published to the App Store by the end of the week.

**Comment by jpegjames** [comment]
I'm closing this one because I the latest release fixed all known issues and I have no reason to conclude at this time that this bug was something different.
