### ISSUE TITLE
Settings don't open on Mojave 10.14.4

### ISSUE THREAD

**Issue by btknorr** [jpegjames/glukey#5]
Settings don't open on Mojave 10.14.4

**Comment by jpegjames** [comment]
Hi @btknorr: Could you confirm that the window isn't just opening behind all of the other windows? I recently noticed that after updating to 10.14.3 the setting window opens behind everything else. I obviously still need to fix this, but I just wanted to confirm that it is the same issue that I'm experiencing.

Thanks,
James

**Comment by hardyjohnson** [comment]
I can confirm on my 10.14.4 settings opens behind the active window, not necessarily all windows. v1.1.1.

**Comment by jpegjames** [comment]
This bug has been fixed and is awaiting review on the App Store. Sorry for the delay.

**Comment by jpegjames** [comment]
@hardyjohnson: The latest version is now available in the App Store and fixes this issue. Thanks again for the feedback.

**Comment by hardyjohnson** [comment]
Awesome thank you @jpegjames. I use this everyday.
