### ISSUE TITLE
Crashes after start

### ISSUE THREAD

**Issue by tersor** [jpegjames/glukey#6]
The application starts as normal after downloading, but the settings window is behind other windows (as mentioned in #5).

But after saving options, the app crashes. It continue to crash seconds after trying to start again. Details in [this crash report](https://gist.github.com/tersor/10389022f3120edcdca87ae16fb348cd).

I used my Dexcom username in the username field (and not email address).

**Comment by jpegjames** [comment]
Hey @tersor,

Sorry for the delay—this was posted right at the beginning of a long vacation where I was out of pocket for a while. I believe I have found the bug. It crashes when there is more than 24 hours of no data. I have fixed it on my end and want to track #5 before resubmitting to the App Store (hopefully later this week). 

I will close this one once it is live on the App Store and let you know. 

Thanks,
James

**Comment by jpegjames** [comment]
Hi @tersor,

Again for the sorry for the delay. I believe this bug has been fixed. The app is awaiting review on the App Store and should be live soon. I will comment here again when the update is published.

**Comment by jpegjames** [comment]
Hi @tersor: The latest version is now available in the App Store and I'm 99% sure it fixed your specific issue. However, if you still have an issue, please reopen and late me know. 

Thanks again for the feedback!
