### ISSUE TITLE
Monterey

### ISSUE THREAD

**Issue by amymarie2688** [jpegjames/glukey#8]
I have been using and loved Glukey to for easy access to my number while working, since I updated to Monterey a few days ago I cannot get it to load.  It acts like it will open and doesn't actually open.  I have tried removing and reinstalling but that didn't help.

**Comment by jpegjames** [comment]
Hi @amymarie2688, I'm running into the same issue myself. Some change with the Dexcom data is causing GluKey to crash, but I don't yet have a fix. I hope to find the solution soon.

**Comment by tersor** [comment]
Same issue here.

**Comment by tbishop56** [comment]
Hi James, I have the same issue. Glukey is a wonderful little applet that I use constantly. However, since upgrading to Monterey it has not been able to run without crashing. If you have a beta and want me to test it out, then let me know. 

Keep up the good work.

**Comment by jpegjames** [comment]
Hi @amymarie2688, @tersor and @tbishop56:

I'm sorry for the delay in getting back to you. I was unavailable for the past month. I've added more info in #2, but the fix has been submitted to the App Store. You should be able to update GluKey on your computer and it work again.

Thanks,
James
